src/api/urls.py
from django.urls import path, include
from rest_framework_simplejwt.views import TokenRefreshView
from . import views


app_name = "api"

urlpatterns = [
    
    # User  urls
    path('user/', include(("api.users.urls", "api-users")), name='api_users'),

    # Product urls
    path('product/', include(("api.product.urls", "api-product")), name='api_product'),

    # Blog urls
    path("blog/", include(("api.blog.urls", "api-blog")), name="api_blog"),
    
    # Cart
    path('cart/', include('api.cart.urls', "api-urlscart"), name="api_cart"),

    path('about/statistics', views.StatisticsAPIView.as_view(), name="statistics"),
    
    path('about/sponsor', views.AboutSponsorsListApiView.as_view(), name="sponsors"),
    
    path('about/staff', views.AboutStaffListApiView.as_view(), name="staffs"),
]

src/api/users/urls.py
from django.urls import path
from api.users import views
from rest_framework_simplejwt.views import TokenRefreshView
from knox import views as knox_views



urlpatterns = [

    # User APIs
    path('login', views.LoginUserApiView.as_view(), name="login"),
    path('login/refresh', TokenRefreshView.as_view(), name='token_refresh'),
    path('register', views.UserCreateView.as_view(), name='register'),
    path('change-profilepic', views.UpdateProfilePicAPIView.as_view(), name='change_profilepic'),
    path('change-password', views.PasswordUpdateView.as_view(), name='change_password'),

]

src/cart/urls.py
from django.urls import path

from cart import views

app_name = 'carts'


urlpatterns = [
    path('shopping-cart', views.shopping_cart, name = 'shopping-cart'),
    path("check_basket/", views.check_basket, name="check_basket"),
    path("update_item/", views.update_item, name="update_item"),
    path("whislist/", views.whislist, name="whislist"),
]

src/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path("", views.home, name = 'home'),
    path("about", views.about, name = 'about'),
    # path("contact", views.ContactUs.as_view(), name = 'contact'),
    path("contact", views.contact, name = 'contact'),
]

src/pavshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.i18n import i18n_patterns

# from django.conf.urls import include
from django.urls import re_path
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView



urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin/', admin.site.urls),
    
    path('api/', include('api.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    # Optional UI:
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),

    path('', include('core.urls', namespace='core')),
    path('', include('users.urls')),
    path('blogs/', include('blog.urls', namespace='blogs')),
    path('accounts/', include('users.urls', namespace="users")),
    # path('accounts/', include('allauth.urls')),
    path('', include('order.urls')),
    path('products/', include('product.urls')),
    path('cart/', include('cart.urls')),


    re_path(r'^rosetta/', include('rosetta.urls')),

    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="users/password/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password/password_reset_complete.html'), name='password_reset_complete'),

    path('oauth/', include('social_django.urls', namespace='social')),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)


# if 'rosetta' in settings.INSTALLED_APPS:
#     urlpatterns += [
#         re_path('rosetta/', include('rosetta.urls'))
#     ]

urlpatterns = [
    *i18n_patterns(*urlpatterns, prefix_default_language=False),
    # path("<str:language>/<path:path>/", core_view.set_language, name="set-language"),
    path('i18n/', include('django.conf.urls.i18n')),
]

src/users/urls.py
from re import template
# from django.contrib.auth import views as auth_views
from django.urls import path
from django.contrib.auth import views as auth_views #import this

from . import views 

app_name = 'users' 

urlpatterns = [
    path('login', views.login_user, name='login'),
    path('login-social', views.login_social, name='login_social'),    
    path('register', views.register_user, name='register'),
    path('profile', views.user_profile, name='profile'),

    path('confirmation/<str:uuidb64>/<str:token>/', views.confirmation, name='confirmation'),

    # path('/password', auth_views.PasswordChangeView.as_view(template_name='users/profile.html'), name='password'),
    path('password', views.user_profile, name = 'change_password'),
    path('callback', views.callback, name='callback'),
    path('logout', views.logout_user, name='logout_user'),    
    path("password_reset", views.password_reset_request, name="password_reset")
]

src/users/models.py
import datetime
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.utils import timezone

# User table
class User(AbstractUser):
    COUNTRY_CHOICES = (
    ('azerbaijan','AZERBAIJAN'),
    ('turkey', 'TURKEY'),
    ('russia','RUSSIA'),
    ('america','AMERICA'),
    )
    GENDER_CHOICES = (
        ("w", "woman"),
        ("m", "man"),
    )   

    username = models.CharField(
        ("username"),
        null=True, blank=True,
        max_length=150,
        unique=True,
        help_text=(
            "Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only."
        ),
        error_messages={
            "unique": ("A user with that username already exists."),
        },
    )
    profile_image = models.ImageField(upload_to="user", default="users/default-pp/avatar-1.jpg", null=True, blank=True)
    first_name = models.CharField(
        ("first name"), 
        max_length=255, 
        blank=True
    )
    last_name = models.CharField(
        ("last name"), 
        max_length=255, 
        blank=True
    )
    address = models.TextField(
        null=True,
        blank=True
    )
    country = models.CharField(
        max_length=10, 
        choices=COUNTRY_CHOICES, 
        default='green', 
        blank=True
    )
    city = models.CharField(
        max_length=128,
        null=True,
        blank=True
    )
    email = models.EmailField(
        ("email address"), 
        max_length=255, 
        unique=True,
    )
    gender = models.CharField(
        max_length=50,
        choices=GENDER_CHOICES,  
        null=True, 
        blank=True
    )
    phone = models.CharField(
        max_length=50,
        null=True,
        blank=True
    ) 
    phone_prefix = models.ForeignKey(
        "users.PhonePrefix",
        related_name="users",
        blank=True,
        null=True,
        on_delete=models.DO_NOTHING,
    )
    zip_code = models.IntegerField(
        null=True, 
        blank=True
    )
    is_staff = models.BooleanField(
        ("staff status"),
        default=False,
        help_text=("Designates whether the user can log into this admin " "site."),
    )
    birth_date = models.DateField(
        blank=True, 
        null=True,
    )
    date_joined = models.DateTimeField(
        ("date joined"), 
        default=timezone.now,
    )
    last_login = models.DateTimeField(
        null=True, 
        blank=True, 
        default=datetime.datetime.now(),
    )

    # def save(self, *args, **kwargs) -> None:
    #     self.username = self.first_name + self.last_name + 'kerim'
    #     super(User, self).save(*args, **kwargs)

    @property
    def full_name(self) -> str:
        return '%s %s' % (self.first_name, self.last_name)

    def __str__(self) -> str:
        return self.full_name

    class Meta:
        verbose_name = "user"
        indexes = [
            models.Index(fields=['first_name', 'last_name']),
            models.Index(fields=['first_name'], name='first_name_idx'),
        ]


# --------------------------------------------

class Blogger(User):
    class Meta:
        proxy = True
    
    def __str__(self):
        return f"{self.full_name}"


# --------------------------------------------
class MyUser(User):
    class Meta:
        proxy = True
    
    def __str__(self):
        return f"{self.full_name}"
        
# --------------------------------------------
# class Designer(User):
# --------------------------------------------

class PhonePrefix(models.Model):
    prefix = models.CharField(max_length=10, unique=True)
    
    # moderation
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.prefix}"



# --------------------------------------------       

class UserNotification(models.Model):
    """
    This model is used for as ref_obj for myuser model object.
    """
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="user_notification",
        on_delete=models.CASCADE,
    )
    mail_sent = models.BooleanField(default=False)

    # moderation
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.user}"

src/users/forms.py
from django.forms import ModelForm
from django import forms
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth import get_user_model

User = get_user_model()

class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'phone', 'password1', 'address', 'country', 'city', 'password2')

        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control col-lg-6', 'style': 'display:block;'}),
            'email': forms.EmailInput(attrs={'class': 'form-control col-lg-6', 'style': 'display:block;'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control'}),
            'city': forms.TextInput(attrs={'class': 'form-control'}),
            'country': forms.Select(attrs={'class': 'selectpicker'}),
            'address': forms.Textarea(attrs={'class': 'form-control'}),
        }

        labels ={
            'first_name': '*FIRST NAME',
            'email': '*EMAIL',
            'last_name': '*LAST NAME',
            'password': '*PASSWORD',
            'phone': '*PHONE',
            'city': '*TOWN/CITY',
            'country': 'COUNTRY',
            'address': '*ADDRESS',
        }

class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username')

        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control form-control-alternative', 'name': 'first_name', 'initial': 'value'}),
            'last_name': forms.TextInput(attrs={'name': 'last_name', 'class': 'form-control form-control-alternative', 'initial': 'value'}),
            # 'phone': forms.TextInput(attrs={'class': 'form-control form-control-alternative', 'name': 'phone'}),
            'email': forms.EmailInput(attrs={'class': 'form-control form-control-alternative', 'name': 'email', 'initial': 'value'}),
            'username': forms.TextInput(attrs={'class': 'form-control form-control-alternative', 'name': 'username'}),
        }
        labels = {
            'first_name': 'FIRST NAME',
            'email': 'EMAIL',
            'last_name': 'LAST NAME',
        }

        value = {
            'first_name': 'value',
            'last_name': 'value',
            'email': 'value',
        }

class UserPasswordForm(forms.Form):
    labels = {
            'password': 'CURRENT PASSWORD',
            'new_password': 'NEW PASSWORD',
            'new_password_confirmation': 'NEW PASSWORD CONFIRMATION',
        }

    current_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    new_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    new_password_confirmation = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

class PasswordChangingForm(PasswordChangeForm):
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control form-control-alternative', 'type': 'password'}))
    new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control form-control-alternative', 'type': 'password'}))
    new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control form-control-alternative', 'type': 'password'}))

    class Meta:
        model = User
        fields = ('old_password', 'new_password1', 'new_password2')
        labels = {
            'old_password': 'CURRENT PASSWORD',
            'new_password1': 'NEW PASSWORD',
            'new_password2': 'NEW PASSWORD CONFIRMATION',
        }   

src/api/users/views.py
from rest_framework import generics, permissions, status, authentication
from rest_framework_simplejwt.views import TokenObtainPairView
from django.http import JsonResponse
from rest_framework.views import APIView

from api.users.serializers import (
    RegisterSerializer, 
    LoginUserSerializer,
    UserSerializer,
    PasswordChangeSerializer,
    ChangeProfilePicSerializer,
    )
from django.contrib.auth import get_user_model
from rest_framework.response import Response
from django.shortcuts import get_object_or_404
from knox.models import AuthToken

User = get_user_model()



class LoginUserApiView(generics.CreateAPIView):

    """ 
    Endpoint for this api - "api/user/login/"  

    """

    permission_classes = (permissions.AllowAny,)
    serializer_class = LoginUserSerializer

    def post(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)

        if not serializer.is_valid():
            return JsonResponse(serializer.errors, status=400)

        user = serializer.validated_data
        response = JsonResponse(
            {
                "user": UserSerializer(
                    user, context=self.get_serializer_context()
                ).data,
                "token": AuthToken.objects.create(user)[1],
            }
        )

        return response



class UserCreateView(generics.CreateAPIView):
    """ 
    Endpoint for this api - "api/user/register"  

    """

    serializer_class = RegisterSerializer
    queryset = User.objects.all()



class UpdateProfilePicAPIView(generics.UpdateAPIView):
    """
    Endpoint for this api - “api/user/change-profilepic 
    """
    permisson_classes = (permissions.IsAuthenticated,)
    serializer_class = ChangeProfilePicSerializer

    def patch(self, request):
        user = self.request.user
        serializer = self.get_serializer(data=request.data)
        if serializer.is_valid():
            print(serializer.validated_data["new_image"])
            user.profile_image = serializer.validated_data["new_image"]
            print(user.profile_image)
            user.save()
            return Response(
                {"message": "Picture updated successfully"},
                status=status.HTTP_200_OK,
            )
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)




class PasswordUpdateView(generics.UpdateAPIView):
    """
    Endpoint for this api - "api/user/change-password"
    """
    
    serializer_class = PasswordChangeSerializer
    permission_classes = (permissions.IsAuthenticated, )
    
    def update(self, request, *args, **kwargs):
        user = self.request.user
        serializer = self.get_serializer(data=request.data)

        if serializer.is_valid():
            user.set_password(serializer.validated_data["new_password"])
            user.save()
            return Response(
                {"message": "Password updated successfully"},
                status=status.HTTP_200_OK,
            )

        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

src/users/templates/users/login.html
{% extends 'base.html' %} 
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

  {% include 'users/_partials/_user-header.html' %}
  
  <!-- Content -->
  <div id="content"> 
    
    <!--======= PAGES INNER =========-->
    <section class="chart-page padding-top-100 padding-bottom-100">
      <div class="container"> 
        
        <!-- Payments Steps -->
        <div class="shopping-cart"> 
          
          <!-- SHOPPING INFORMATION -->
          <div class="cart-ship-info">
            <div class="row"> 
              
              <!-- ESTIMATE SHIPPING & TAX -->
              <div class="col-sm-7">
                <h6>LOGIN YOUR ACCOUNT</h6>
                <form action="{% url 'users:login' %}" method = 'post' id="login-form">
                  {% csrf_token %}
                  <ul class="row">
                    
                    <!-- Name -->
                    <li class="col-md-12">
                      <label> USERNAME
                        {% comment %} <input type="text" name="first-name" value="" placeholder=""> {% endcomment %}
                        {{ login_form.username }}
                      </label>
                    </li>
                    <!-- LAST NAME -->
                    <li class="col-md-12">
                      <label> PASSWORD
                        {% comment %} <input type="password" name="last-name" value="" placeholder=""> {% endcomment %}
                        {{ login_form.password }}
                      </label>
                    </li>
                    
                    <!-- LOGIN -->
                    <li class="col-md-4">
                      <button type="submit" class="btn">LOGIN</button>
                    </li>
                    
                    <!-- CREATE AN ACCOUNT -->
                    <p class="text-center">Don't have an account? <a href="register">Create an account</a>.</p>
                    
                    <!-- STAY LOGGED IN -->
                    <li class="col-md-4">
                      <div class="checkbox margin-0 margin-top-20">
                        <input id="checkbox1" class="styled" type="checkbox">
                        <label for="checkbox1"> Stay me Login</label>
                      </div>
                    </li>
                    
                    <!-- FORGET PASS -->
                    <li class="col-md-4">
                      <div class="checkbox margin-0 margin-top-20 text-right">
                        <a href="{% url 'users:password_reset' %}">Forget Password</a>
                      </div>
                    </li>
                  </ul>
                </form>
                
              </div>
              
              <!-- SUB TOTAL -->
              <div class="col-sm-5">
                <h6>LOGIN WITH</h6>
                
                <ul class="login-with">
                	<li>
                    	<a href="{% url 'social:begin' 'facebook' %}"><i class="fa fa-facebook"></i>FACEBOOK</a>
                    
                    </li>
                    
                    <li>
                    	<a href="{% url 'social:begin' 'google-oauth2' %}"><i class="fa fa-google"></i>GOOGLE</a>
                    
                    </li>
                    
                    <li>
                    	<a href="{% url 'social:begin' 'twitter' %}"><i class="fa fa-twitter"></i>TWITTER</a>
                    
                    </li>
                
                </ul>
                
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    
    <!-- About -->
    <section class="small-about padding-top-150 padding-bottom-150">
      <div class="container"> 
        
        <!-- Main Heading -->
        <div class="heading text-center">
          <h4>about PAVSHOP</h4>
          <p>Phasellus lacinia fermentum bibendum. Interdum et malesuada fames ac ante ipsumien lacus, eu posuere odio luctus non. Nulla lacinia,
            eros vel fermentum consectetur, risus purus tempc, et iaculis odio dolor in ex. </p>
        </div>
        
        <!-- Social Icons -->
        <ul class="social_icons">
          <li><a href="#."><i class="icon-social-facebook"></i></a></li>
          <li><a href="#."><i class="icon-social-twitter"></i></a></li>
          <li><a href="#."><i class="icon-social-tumblr"></i></a></li>
          <li><a href="#."><i class="icon-social-youtube"></i></a></li>
          <li><a href="#."><i class="icon-social-dribbble"></i></a></li>
        </ul>
      </div>
    </section>
    
    {% block js_files %}

      <script>
        $("#login-form")[0].addEventListener('submit', (e) => {
          let csrftoken = $("input[name=csrfmiddlewaretoken]").val();
          
          let formData = {
              'username': $("#id_username").val(),
              'password': $("#id_password").val(),
              'csrfmiddlewaretoken': '{% csrf_token %}'
          }
      
          fetch('http://127.0.0.1:8000/api/user/login', {
              method: 'POST',
              headers: {
                  'Content-Type': 'application/json',
                  'X-CSRFToken': csrftoken,
              },
              body: JSON.stringify(formData)
          })
              .then(response => response.json())
              .then(data => {
                  if (data) {
                    document.cookie ='token=' + JSON.stringify({"token": data.token}) + ";domain=;path=/";
                    $.ajax({
                      method: "POST",
                      url: "{% url 'users:login' %}",
                      data: {
                        csrfmiddlewaretoken: csrftoken,
                        data: formData,
                        },
                      success: function (response) {
                          $("#login-form").trigger('reset');
                      },
                      error: function (response) {
                          // alert the error if any error occured
                          alert("Error");
                      }
                    })
                  } else {
                      alert('Username OR password did not work')
                  }
              }) 
            }) 
      </script>

    {% endblock js_files %}
    
  {% endblock %}

src/users/templates/users/register.html
{% extends 'base.html' %} 
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

  {% include 'users/_partials/_user-header.html' %}
  
  <!-- Content -->
  <div id="content"> 
    
    <!--======= PAGES INNER =========-->
    <section class="chart-page padding-top-100 padding-bottom-100">
      <div class="container"> 
        
        <!-- Payments Steps -->
        <div class="shopping-cart"> 
          
          <!-- SHOPPING INFORMATION -->
          <div class="cart-ship-info register">
            <div class="row"> 
              
              <!-- ESTIMATE SHIPPING & TAX -->
              <div class="col-sm-12">
                <h6>REGISTER</h6>

                <div id="contact_message" class="success-msg">
                  <i class="fa-solid fa-user-check"></i> Thank You. Your have been Registered
                </div>
    
                <div class="alert alert-danger error_message" style="display: none;" role="alert"></div>

                <form action="{% url 'users:register' %}" method='post' class='register_form'>
                  <ul class="row">
                    
                    {% csrf_token %}

                    {{ register_form_errors }}

                    {% comment %} {{ form }} {% endcomment %}
                    <!-- Name -->
                    <li class="col-md-6">
                      <label>{{ register_form.first_name.label }}
                        {{ register_form.first_name }}
                      </label>
                    </li>
                    
                    <!-- LAST NAME -->
                    <li class="col-md-6">
                      <label>{{ register_form.last_name.label }}
                        {{ register_form.last_name }}
                      </label>
                    </li>
                    
                    <!-- EMAIL ADDRESS -->
                    <li class="col-md-6">
                      <label>{{ register_form.email.label }}
                        {{ register_form.email }}
                      </label>
                    </li>

                    <!-- PHONE -->
                    <li class="col-md-6">
                      <label>{{ register_form.phone.label }}
                        {{ register_form.phone }}
                      </label>
                    </li>
                    
                    <!-- PASSWORD -->
                    <li class="col-md-6">
                      <label>{{ register_form.password1.label }}
                        {{ register_form.password1 }}
                        {{ register_form.password1.errors }}
                      </label>
                    </li>
                    
                    <!-- PASSWORD -->
                    <li class="col-md-6">
                      <label>{{ register_form.password2.label }}
                        {{ register_form.password2 }}
                      </label>
                    </li>

                 
                    
                    <!-- ADDRESS -->
                    <li class="col-md-6"> 
                      <label>{{ register_form.address.label }}
                        {{ register_form.address }}
                      </label>
                    </li>
                    
                    <!-- COUNTRY -->
                    <li class="col-md-6">
                      {% comment %} <label> COUNTRY
                        <select class="selectpicker" name="contry-state">
                          <option>COUNTRY</option>
                          <option>Country 2</option>
                          <option>Country 3</option>
                        </select>
                      </label> {% endcomment %}

                      <label>{{ register_form.country.label }}
                        {{ register_form.country }}
                      </label>
                    </li>
                    
                    <!-- TOWN/CITY -->
                    <li class="col-md-6">
                      <label>{{ register_form.city.label }}
                        {{ register_form.city }}
                      </label>
                    </li> 
                    
                    <!-- SUBMIT -->
                    {% comment %} <form method="post">
                      {% csrf_token %}
                      <ul class="row">
                        <li class="col-md-6" style="position: relative; z-index:9999999999;">
                            {{ register_form | crispy }}
                        </li>

                    {% endcomment %}
                    
                    <!-- REGISTER BUTTON -->
                    <li class="col-md-6">
                      <button type="submit" class="btn">REGISTER NOW</button>
                    </li>
                  </ul>
                </form> 
                <p class="text-center">If you already have an account, <a href="{% url 'users:login' %}">login</a> instead.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    
    <!-- About -->
    <section class="small-about padding-top-150 padding-bottom-150">
      <div class="container"> 
        
        <!-- Main Heading -->
        <div class="heading text-center">
          <h4>about PAVSHOP</h4>
          <p>Phasellus lacinia fermentum bibendum. Interdum et malesuada fames ac ante ipsumien lacus, eu posuere odio luctus non. Nulla lacinia,
            eros vel fermentum consectetur, risus purus tempc, et iaculis odio dolor in ex. </p>
        </div>
        
        <!-- Social Icons -->
        <ul class="social_icons">
          <li><a href="#."><i class="icon-social-facebook"></i></a></li>
          <li><a href="#."><i class="icon-social-twitter"></i></a></li>
          <li><a href="#."><i class="icon-social-tumblr"></i></a></li>
          <li><a href="#."><i class="icon-social-youtube"></i></a></li>
          <li><a href="#."><i class="icon-social-dribbble"></i></a></li>
        </ul>
      </div>
    </section>
  </div>

  <script type="text/javascript">

    $(document).on('submit', '.register_form', function(e){
      e.preventDefault();

      var csrf_token = $("input[name='csrfmiddlewaretoken']").val();
      var first_name = $("input[name='first_name']").val();
      var last_name = $("input[name='last_name']").val();
      var email = $("input[name='email']").val();
      var phone = $("input[name='phone']").val();
      var password1 = $("input[name='password1']").val();
      var password2= $("input[name='password2']").val();
      var address = $("textarea[name='address']").val();
      var country = $("select[name='country']").find(":selected").val();
      var city = $("input[name='city']").val();

      let successMessage = $('.success-msg');
      let errorMessage = $('.error_message');
  
      $.ajax({
        type: "POST",
        url: "{% url 'users:register' %}",
        data: {
          'csrfmiddlewaretoken': csrf_token,
          'first_name': first_name,
          'last_name': last_name,
          'password1': password1,
          'password2': password2,
          'email': email,
          'phone': phone,
          'address': address,
          'country': country,
          'city': city,
        },
        success: function(response){
          successMessage.css("display", "block");
          errorMessage.css("display", "none");
          
        },
        error: function(response){
          errorMessage.css("display", "block");  
          successMessage.css("display", "none");
          errorMessage.html("");
          if (response["responseJSON"]["error"]){
            $.each(response["responseJSON"]["error"], function(key, value){
              errorMessage.prepend(
            `
              <p>${response["responseJSON"]["error"][key]}</p>
            `
          ); 
            })
          }
        }
        
      })
    })
  </script>
  
  {% endblock %}