src/api/blog/urls.py
from django.urls import path
from api.blog import views



urlpatterns = [
    # Blog APIs
    path('', views.BlogListAPIView.as_view(), name='blog-list'),
    path('categories', views.BlogCategoryListApiView.as_view(), name='blog-categories'),
    path('popular-tags/', views.PopularBlogTagsListAPIView.as_view(), name="blog_tags"),
    path('last-blogs/', views.LastBlogsListAPIView.as_view(), name="last_blogs"),
]

src/api/urls.py
from django.urls import path, include
from rest_framework_simplejwt.views import TokenRefreshView
from . import views


app_name = "api"

urlpatterns = [
    
    # User  urls
    path('user/', include(("api.users.urls", "api-users")), name='api_users'),

    # Product urls
    path('product/', include(("api.product.urls", "api-product")), name='api_product'),

    # Blog urls
    path("blog/", include(("api.blog.urls", "api-blog")), name="api_blog"),
    
    # Cart
    path('cart/', include('api.cart.urls', "api-urlscart"), name="api_cart"),

    path('about/statistics', views.StatisticsAPIView.as_view(), name="statistics"),
    
    path('about/sponsor', views.AboutSponsorsListApiView.as_view(), name="sponsors"),
    
    path('about/staff', views.AboutStaffListApiView.as_view(), name="staffs"),
]

src/blog/urls.py
from django.urls import path
from . import views

app_name = "blogs"

urlpatterns = [
    path('', views.BlogListView.as_view(), name='blogs'),
    path('<slug:slug>/', views.blog_detail, name='blog-detail')
]

src/pavshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.i18n import i18n_patterns

# from django.conf.urls import include
from django.urls import re_path
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView



urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin/', admin.site.urls),
    
    path('api/', include('api.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    # Optional UI:
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),

    path('', include('core.urls', namespace='core')),
    path('', include('users.urls')),
    path('blogs/', include('blog.urls', namespace='blogs')),
    path('accounts/', include('users.urls', namespace="users")),
    # path('accounts/', include('allauth.urls')),
    path('', include('order.urls')),
    path('products/', include('product.urls')),
    path('cart/', include('cart.urls')),


    re_path(r'^rosetta/', include('rosetta.urls')),

    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="users/password/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password/password_reset_complete.html'), name='password_reset_complete'),

    path('oauth/', include('social_django.urls', namespace='social')),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)


# if 'rosetta' in settings.INSTALLED_APPS:
#     urlpatterns += [
#         re_path('rosetta/', include('rosetta.urls'))
#     ]

urlpatterns = [
    *i18n_patterns(*urlpatterns, prefix_default_language=False),
    # path("<str:language>/<path:path>/", core_view.set_language, name="set-language"),
    path('i18n/', include('django.conf.urls.i18n')),
]

src/blog/models.py
from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from django.urls import reverse
from ckeditor.fields import RichTextField
from django.contrib.postgres.fields import JSONField
from django.conf import settings

from tools.unique_slug import unique_slug_generator


class Tag(models.Model):
    name = models.CharField(max_length=255)
    usage_count = models.IntegerField(default=0)
    
    # moderation
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name



class Blog(models.Model):
    title = models.CharField(
        max_length=255,
        null=False,
    )
    slug = models.SlugField(
        max_length=255, 
        null=True, 
        blank=True, 
        unique=True, 
        editable=False, 
        db_index=True
    )
    author = models.ForeignKey(
        "users.Blogger",
        related_name="blogs",
        null=True,
        blank=True,
        on_delete=models.CASCADE,
    )
    text = RichTextField(
        null=False,
        blank=True
    )
    image = models.ImageField(
        upload_to="blogs/%Y/%m/%d/", 
        null=True,
        blank=True,
    )
    tags = models.ManyToManyField(
        Tag,
        related_name="blogs",
        through="BlogTag",
    )
    category = models.ForeignKey(
        "product.Category",
        related_name="blogs",
        null=False,
        blank=True,
        on_delete=models.CASCADE,
    )
    read_count = models.IntegerField(
        null=True,
        default=0,
    )

    # moderation
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    class Meta:
        verbose_name_plural="blogs"

    def __str__(self) -> str:
        return self.title

    def save(self, *args, **kwargs) -> None:
        if not self.slug:
            self.slug = unique_slug_generator(self, slugify(f"{self.category.name}-{self.title}", allow_unicode=True))
        super().save(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse('blogs:blog-detail', kwargs={'slug': self.slug}) #FIXME view changed with api
    
    
# TODO we can delete the useless fields
class Comment(models.Model):
    comment = models.ForeignKey(
        Blog,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name="comments",
    )
    name = models.CharField(
        max_length=128, 
        null=True,
    )
    email = models.EmailField(
        null=True, 
        blank=True,
    )
    subject = models.CharField(
        max_length=255, 
        null=False,
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        null=True, 
        blank=True,
        related_name="comments",
    )
    comment_text = models.TextField(
        null=False,
        blank=True,
    )
    parent = models.ForeignKey(
        'self', 
        null=True, 
        related_name='replies', 
        on_delete=models.CASCADE, 
        blank=True,
    )

    # moderation
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self) -> str:
        return f"{self.author} {self.name}"


class BlogTag(models.Model):
    tag_name = models.ForeignKey(Tag, on_delete=models.CASCADE, related_name="blogtag",)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name="blogtag",)

    # moderation
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.tag_name.name

src/blog/forms.py
from django import forms
from django.forms import ModelForm

from .models import Comment


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('comment', 'parent', 'name', 'email', 'subject', 'comment_text')

        widgets = {
            'comment': forms.HiddenInput(attrs={'initial': 'value'}),
            'parent': forms.HiddenInput(attrs={'name': 'parent_id', 'initial': 'value'}),
            'name': forms.TextInput(attrs={'class': 'form-control', 'name': 'name'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'required': 'required', 'name': 'email'}),
            'subject': forms.TextInput(attrs={'class': 'form-control', 'name': 'subject'}),
            'comment_text': forms.Textarea(attrs={'class': 'form-control', 'rows':4, 'cols':15, 'name': 'comment_text'}),
        }
        labels = {
            'name': 'NAME',
            'email': 'EMAIL',
            'subject': 'SUBJECT',
            'comment_text': 'COMMENTS'
        }
    
        value = {
            'comment': 'value'
        }

    def clean(self):
        cleaned_data = super().clean()
        email = self.cleaned_data['email']
        if email is not None:
            if len(email) < 10:
                raise forms.ValidationError('Your email is too short')

        return cleaned_data

class SearchForm(forms.Form):
    search_text = forms.CharField(max_length=128, widget=forms.TextInput(attrs={'placeholder': 'SEARCH', 'class': 'form-control', 'name': 'search_text'}))
        

src/api/blog/views.py
from rest_framework import generics, permissions, status
from api.blog.serializers import (
    BlogSerializer,
    BlogTagSerializer,
)
from api.product.serializers import CategorySerializer
from blog.models import (
    Tag,
    Blog,
    Comment,
    BlogTag,
)
from product.models import Category


class BlogListAPIView(generics.ListAPIView):
    """
    Endpoint for this api - "api/blog/"
                            "api/blog/?recent=true/"
                            "api/blog/?popular=true/"
                            "api/blog/?category=<str>/"
    """
    permission_classes = (permissions.AllowAny,)
    serializer_class = BlogSerializer
    
    def get_queryset(self):
        recent_blogs = self.request.query_params.get("recent") 
        popular_blogs = self.request.query_params.get("popular") 
        blog_category = self.request.query_params.get("category")

        queryset = Blog.objects.all().order_by("-created_at")
        if recent_blogs:
            queryset = queryset[:5]
        if popular_blogs:
            queryset = queryset.filter("-read_count")
        if blog_category:
            category = Category.objects.get(name=blog_category.lower())
            queryset = category.blogs

        return queryset




class BlogCategoryListApiView(generics.ListAPIView):
    """
    Endpoint for this api - "api/blog/categories"
    LIst of blog categories
    """
    permission_classes = (permissions.AllowAny,)
    queryset = Category.objects.all()
    serializer_class = CategorySerializer
    pagination_class = None
    # TODO blogcategory ni product categoryden ayirmaq ucun extra fieldi yarat


class PopularBlogTagsListAPIView(generics.ListAPIView):
    """
    Endpoint for this api - "api/blog/popular-tags/"
    List of 5 popular blog tags
    """
    queryset = BlogTag.objects.all().order_by("-tag_name__usage_count")[:5]
    serializer_class = BlogTagSerializer
    pagination_class = None



class LastBlogsListAPIView(generics.ListAPIView):
    """
    Endpoint for this api - "api/blog/popular-tags/"
    LIst of 2 popular blogs
    """
    queryset = Blog.objects.all().order_by("-read_count")[:2]
    serializer_class = BlogSerializer
    pagination_class = None

src/blog/views.py
from django.shortcuts import render
from django.http.request import HttpRequest
from django.http.response import HttpResponse
from blog.services.blogs import get_blog_by_id, get_comments, recent_blogs, blog_list_pagination, get_category_blog, get_similar_blog, list_comment, popular_blog, get_blog, get_tags, list_tag, list_blog, get_blog_id_with_slug, get_all_categories, get_blog_categories
from blog.forms import CommentForm, SearchForm
from product.services.products import newest_product
from django.core.paginator import Paginator

from django.views.generic import ListView
from blog.models import Blog
from typing import Any, Dict

from django.views.decorators.cache import cache_page
from core.models import Background

# Global variable
recent_blogs_posts = recent_blogs()


class BlogListView(ListView):
    model = Blog
    object_list = Blog.objects.all()
    

    def get_context_data(self, *, object_list=None, **kwargs) -> Dict[str, Any]:
        queryset = object_list if object_list is not None else self.object_list.order_by("-read_count")
        categories = get_all_categories()
        tags = list_tag()
        new_product = newest_product()
        # page_size = self.get_paginate_by(queryset)
        context_object_name = self.get_context_object_name(queryset)
        paginator = blog_list_pagination()
        page_number = self.request.GET.get('page', 1)
        background = Background.objects.all()[0].blog_page
        page_obj = paginator.get_page(page_number)
        context = {
                'paginator': paginator,
                'page_obj': page_obj,
                'blogs': queryset,
                'recent_blogs': recent_blogs_posts,
                "categories": categories,
                "tags": tags,
                "new_product": new_product,
                "background": background
            }
     
        if context_object_name is not None:
            context[context_object_name] = queryset
        context.update(kwargs)
        return super().get_context_data(**context)


def blog_detail(request: HttpRequest, slug) -> HttpResponse: 
    id = get_blog_id_with_slug(slug).id
    blog = get_blog_by_id(id)
    comments = get_comments(id)
    categories = get_all_categories()
    blogtags = list_tag()
    new_product = newest_product()
    similar_blogs = get_similar_blog(id, blog.category)
    search_form = SearchForm()
    comment_form = CommentForm(initial={"comment": id})
    if request.user.is_authenticated:
        comment_form = CommentForm(initial={"comment": id, "name": request.user.full_name, "email": request.user.email})
    if request.method == "POST":
        parent_id = request.POST.get('parent')
        form = CommentForm(request.POST, initial={"comment": id, "parent": parent_id})
        if form.is_valid():
            form.save()
    
    context = {
        'blog': blog,
        'title': 'Blog Detail',
        'comment_form': comment_form,
        'search_form': search_form,
        'blog_id': id,
        'comments': comments,
        'recent_blogs': recent_blogs_posts,
        "categories": categories,
        "similar_blogs":similar_blogs,
        "blogtags":blogtags,
        "new_product": new_product,
    }
    return render(request, 'blog/blog_detail.html', context=context)

src/blog/templates/blog/blog_list.html
{% extends 'base.html' %} {% load static %} {% load widget_tweaks %} {% block content %}

<!--======= SUB BANNER =========-->
<section class="sub-bnr" data-stellar-background-ratio="0.5" style="background: url('{{ background.url }}')">
  <div class="position-center-center">
    <div class="container">
      <h4>PAVSHOP blog list</h4>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec faucibus
        maximus vehicula. Sed feugiat, tellus vel tristique posuere, diam
      </p>
      <ol class="breadcrumb">
        <li><a href="/">Home</a></li>
        <li class="active">BLOG</li>
      </ol>
    </div>
  </div>
</section>

<!-- Content -->
<div id="content">
  <!-- Blog List -->
  <section class="blog-list blog-list-3 padding-top-100 padding-bottom-100">
    <div class="container">
      <div class="row">
        <div class="col-md-9">
        {% if searched_blog.count > 0 %}
          {% for blog in searched_blog %}
            <!-- Article -->
            <article>
              <div class="row">
                <div class="col-sm-5">
                  <!-- Post Img -->
                  <img
                    class="img-responsive"
                    src="{{ blog.image.url }}"
                    alt=""
                  />
                </div>
                <div class="col-sm-7">
                  <!-- Tittle -->
                  <div class="post-tittle left">
                    <a href="{{ blog.get_absolute_url }}" class="tittle">{{ blog.title }}</a>
                    <!-- Post Info -->
                    <span><i class="primary-color icon-user"></i> by {{ blog.author }} </span>
                    <span><i class="primary-color icon-calendar"></i> {{ blog.created_at|date:"F j, Y" }} </span>

                      <span><i class="primary-color icon-bubble"></i>{{ blog.comments.count }}</span>
              

                  <span><i class="primary-color icon-tag"></i> {{ blog.category }}</span>
                  </div>
                  <!-- Post Content -->
                  <div class="text-left">
                    <p style="word-break: break-all;">
                      {{ blog.text }}
                    </p>
                    {% comment %} {% url 'blog:blog-detail' blog.slug %} {% endcomment %}
                    <a href="{{ blog.get_absolute_url }}" class="red-more">READ MORE</a>
                  </div>
                </div>
              </div>
            </article>
          {% endfor %}
        {% elif searched_blog.count == 0 %}
        <p class="text-center"> Blog not found </p>
        {% else %}
            {% for blog in page_obj %}
              <!-- Article -->
              <article>
                <div class="row">
                  <div class="col-sm-4">
                    <!-- Post Img -->
                    <img
                      class="img-responsive"
                      src="{{ blog.image.url }}"
                      alt=""
                      width = 370
                      height = 325
                    />
                  </div>
                  <div class="col-sm-8">
                    <!-- Tittle -->
                    <div class="post-tittle left">
                      <a href="{{ blog.get_absolute_url }}" class="tittle">{{ blog.title }}</a>
                      <!-- Post Info -->
                      <span><i class="primary-color icon-user"></i> by {{ blog.author }}</span>
                      <span
                        ><i class="primary-color icon-calendar"></i> {{ blog.created_at|date:"F j, Y" }} </span>
                   
                        <span><i class="primary-color icon-bubble"></i> {{ blog.comments.count }}</span>

                      
                      <span><i class="primary-color icon-tag"></i> {{ blog.category }}</span>
                    </div>
                    <!-- Post Content -->
                    <div class="text-left">
                      <p style="word-break: break-all;"=>
                        {{ blog.text|safe|truncatechars:200 }}
                      </p>
                      {% comment %} {% url 'blog:blog-detail' blog.slug %} {% endcomment %}
                      <a href="{{ blog.get_absolute_url }}" class="red-more">READ MORE</a>
                    </div>
                  </div>
                </div>
              </article>
          {% endfor %}
        {% endif %}
          



          <!-- Pagination -->
          <ul class="pagination in-center">
            {% if page_obj.has_previous %}
            <li><a href="?page=1">&laquo;</a></li>
            <li>
              <a href="?page={{ page_obj.previous_page_number }}"
                ><i class="fa fa-angle-left"></i
              ></a>
            </li>
            {% endif %} 
            {% for page in page_obj.paginator.page_range %} 
              {% if page == page_obj.number %}
                <li class="active">
                  <a href="?page={{page}}">{{page}}</a>
                </li>
              {% else %}
                <li><a href="?page={{page}}">{{page}}</a></li>
              {% endif %} 
            {% endfor %} 
            {% if page_obj.has_next %}
            <li>
              <a href="?page={{ page_obj.next_page_number }}"
                ><i class="fa fa-angle-right"></i
              ></a>
            </li>
            <li>
              <a href="?page={{ page_obj.paginator.num_pages }}">
                &raquo;</a
              >
            </li>
            {% endif %}
          </ul>
        </div>

        <!-- Sider Bar -->
        <div class="col-md-3">
          <!-- SEARCH -->
          <form class="search" method="get" id="search-form">
            {% comment %} {% csrf_token %} {% endcomment %}
            {% comment %} <input name='a'> {% endcomment %}
            {% comment %} {% render_field search_blog_form.search_text name='a' %} {% endcomment %}
            {{ search_blog_form.search_text }}
            {% comment %} {{ search_blog_form.search_text }} {% endcomment %}
            <button class = "search-btn" type="submit"><i class="fa fa-search"></i></button>
          </form>
          <div class="shop-sidebar">

            <!-- Category -->
            <h5 class="shop-tittle margin-bottom-30">category</h5>
            <ul class="shop-cate">
              {% for category in categories %}
                <li>
                  <a href="{{ category.id }}"><span>{{ category }}</span></a>
                </li>
              {% endfor %}
            </ul>


            <!-- TAGS -->
            <h5 class="shop-tittle margin-top-60 margin-bottom-30">
              PAUPLAR TAGS
            </h5>
            <ul class="shop-tags">
              {% for tag in tags %}
                <li><a href="{{tag.id}}">{{ tag }}</a></li>
              {% endfor %}
            </ul>

            <!-- BRAND -->
            <h5 class="shop-tittle margin-top-60 margin-bottom-30">archives</h5>
            <ul class="shop-cate">
              <li><a href="#."> January 2015 </a></li>
              <li><a href="#."> February 2015 </a></li>
              <li><a href="#."> March 2015 </a></li>
              <li><a href="#."> April 2015 </a></li>
              <li><a href="#."> May 2015 </a></li>
            </ul>
            
                        <!-- Recent Post -->
                        <h5 class="shop-tittle margin-top-60 margin-bottom-30">
                          recent post
                        </h5>
                        <ul class="papu-post margin-top-20">
                          {% for recent_blog in recent_blogs %}
                            <li class="media">
                              <div class="media-left">
                                <a href="{{ recent_blog.get_absolute_url }}">
                                  <img class="media-object" src="{{ recent_blog.image.url }}" alt=""
                                /></a>
                              </div>
                              <div class="media-body">
                                <a class="media-heading" href="{{ recent_blog.get_absolute_url }}"
                                  >{{ recent_blog.title }}</a
                                >
                                <span>Posted on {{ recent_blog.created_at|date:'M j' }}</span>
                              </div>
                            </li>
                          {% endfor %}
                        </ul>
            
            <!-- SIDE BACR BANER -->
            <div class="side-bnr margin-top-100">
              <img class="img-responsive" src="{{ new_product.main_image.url }}" alt="" />
              <div class="position-center-center">
                <span class="price"><small>$</small>{{ new_product.price }}</span>
                <div class="bnr-text"><a href="{{ new_product.id }}">look hot with style</a></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Culture BLOCK -->
  <section class="cultur-block">
    <ul>
      <li><img src="{% static 'images/cultur-img-1.jpg' %}" alt="" /></li>
      <li><img src="{% static 'images/cultur-img-2.jpg' %}" alt="" /></li>
      <li><img src="{% static 'images/cultur-img-3.jpg' %}" alt="" /></li>
      <li><img src="{% static 'images/cultur-img-4.jpg' %}" alt="" /></li>
    </ul>

    <!-- Culture Text -->
    <div class="position-center-center">
      <div class="container">
        <div class="col-sm-6 center-block">
          <h4>FOLLOW US @ INSTAGRAM</h4>
          <p>
            Phasellus lacinia fermentutm bibendum. Interdum et malante ipuctus
            non. Nulla lacinia, eros vel fermentum consectetur, ris dolor in ex.
          </p>
        </div>
      </div>
    </div>
  </section>
{% endblock %} {% block js_files %} {% endblock %}