src/api/urls.py
from django.urls import path, include
from rest_framework_simplejwt.views import TokenRefreshView
from . import views


app_name = "api"

urlpatterns = [
    
    # User  urls
    path('user/', include(("api.users.urls", "api-users")), name='api_users'),

    # Product urls
    path('product/', include(("api.product.urls", "api-product")), name='api_product'),

    # Blog urls
    path("blog/", include(("api.blog.urls", "api-blog")), name="api_blog"),
    
    # Cart
    path('cart/', include('api.cart.urls', "api-urlscart"), name="api_cart"),

    path('about/statistics', views.StatisticsAPIView.as_view(), name="statistics"),
    
    path('about/sponsor', views.AboutSponsorsListApiView.as_view(), name="sponsors"),
    
    path('about/staff', views.AboutStaffListApiView.as_view(), name="staffs"),
]

src/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path("", views.home, name = 'home'),
    path("about", views.about, name = 'about'),
    # path("contact", views.ContactUs.as_view(), name = 'contact'),
    path("contact", views.contact, name = 'contact'),
]

src/pavshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.i18n import i18n_patterns

# from django.conf.urls import include
from django.urls import re_path
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView



urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin/', admin.site.urls),
    
    path('api/', include('api.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    # Optional UI:
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),

    path('', include('core.urls', namespace='core')),
    path('', include('users.urls')),
    path('blogs/', include('blog.urls', namespace='blogs')),
    path('accounts/', include('users.urls', namespace="users")),
    # path('accounts/', include('allauth.urls')),
    path('', include('order.urls')),
    path('products/', include('product.urls')),
    path('cart/', include('cart.urls')),


    re_path(r'^rosetta/', include('rosetta.urls')),

    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="users/password/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password/password_reset_complete.html'), name='password_reset_complete'),

    path('oauth/', include('social_django.urls', namespace='social')),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)


# if 'rosetta' in settings.INSTALLED_APPS:
#     urlpatterns += [
#         re_path('rosetta/', include('rosetta.urls'))
#     ]

urlpatterns = [
    *i18n_patterns(*urlpatterns, prefix_default_language=False),
    # path("<str:language>/<path:path>/", core_view.set_language, name="set-language"),
    path('i18n/', include('django.conf.urls.i18n')),
]

src/core/models.py
from django.db import models


# Backgrounds table for each page
class Background(models.Model):
    home_page = models.ImageField(default = "about/home.png", upload_to = "about")
    about_page = models.ImageField(default = "about/about.png", upload_to = "about")
    contact_page = models.ImageField(default = "contact/contact-us.jpeg", upload_to = "contact")
    blog_page = models.ImageField(default = "blog/blog-bg.jpeg", upload_to = "blog-bg")
    product_page = models.ImageField(default = "products/products-list-bg.jpeg", upload_to="products")
    order_page = models.ImageField(default = "order/payment-card.jpeg", upload_to = "order")
    login_register_page = models.ImageField(default = "users/login-register.jpeg", upload_to = "users")
    cart_page = models.ImageField(default="cart/view-cart.jpeg", upload_to="cart")

# Only site users can be subscriber :/
class Subscription(models.Model):
    subscription_email = models.EmailField(
        max_length=128,
        null=True,
        blank=True,
    )

    # moderation
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.subscription_email

    class Meta:
        verbose_name = 'subscription'

# WHY WE NEED THIS TABLE?
class Contact(models.Model):
    full_name = models.CharField(
        max_length=128, 
        null=True,
        blank=True,
    )
    email = models.EmailField(
        max_length=128, 
        blank=True,
        null=True
    )
    phone = models.CharField(
        max_length=10,
        null=True,
        blank=True,
    )
    subject = models.CharField(
        max_length=255,
        null=True,
        blank=True,
    )
    message = models.TextField(
        null=True,
        blank=True,
    )

    # moderation
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

# WE DON'T NEED THIS TABLE!! FIXME
class Staff(models.Model):
    full_name = models.CharField(max_length=255)

    facebook_url = models.CharField(max_length=255, null=True)
    twitter_url = models.CharField(max_length=255, null=True)
    website_url = models.CharField(max_length=255, null=True)

    email = models.EmailField()
    image = models.ImageField(
        upload_to="staff_images/%Y/%m/%d/",
        null=True,
        blank=True,
    )
    position = models.CharField(max_length=255)
    description = models.TextField(
        null=True,
        blank=True,
        )

    class Meta:
        verbose_name = "staff"
        verbose_name_plural = "staff"
    # facebook_url = models.CharField(max_length=255)
    # twitter_url = models.CharField(max_length=255)
    # website_url = models.CharField(max_length=255)
    def __str__(self) -> str:
        return self.full_name

# Home slider table
class Slider(models.Model):
    title = models.CharField(max_length = 255, null = True)
    description = models.CharField(max_length = 300, null = True)
    price = models.FloatField()
    product_link = models.CharField(max_length = 255, null = True)
    image = models.ImageField(null = True, upload_to = "core")

class Feedback(models.Model):
    text = models.TextField(null=True)
    author = models.CharField(max_length=200, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

class Sponsor(models.Model):
    image = models.ImageField(upload_to="sponsors")

class AwesomeCulture(models.Model):
    image = models.ImageField(upload_to="cultures")

class About(models.Model):
    main_image = models.ImageField(upload_to="about-page")
    about_header_text = models.TextField()
    about_footer_text = models.TextField()

src/core/forms.py
import re
from django import forms
from django.forms import ModelForm
from .models import Contact
from django.core.validators import RegexValidator, EmailValidator
from core.models import Subscription


# Subscription form on base.html
class SubscriptionForm(ModelForm):
    class Meta:
        model = Subscription
        fields = ("subscription_email", )
    
        widgets = {
            'subscription_email': forms.TextInput(attrs={'class': 'form-control', "placeholder": "Enter your email address"}),
        }


# Contact form on contact.html
class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

        widgets = {
            'full_name': forms.TextInput(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'username@example.com'}),
            'subject': forms.TextInput(attrs={'class': 'form-control'}),
            'message': forms.Textarea(attrs={'class': 'form-control', 'rows':4, 'cols':40}),
        }
        labels = {
            'full_name': '*FULL NAME',
            'email': '*EMAIL',
            'phone': '*PHONE',
            'subject': '*SUBJECT',
            'message': '*COMMENTS'
        }

        required = (
            'email',
            'full_name',
            'phone',
            'subject',
            'message'
        )

        validators ={
            'email': [RegexValidator('[a-zA-z0-9_\-\.]+[@][a-z]+[\.][a-z]{2,3}', message='Enter an email in correct format')],
            'phone': [RegexValidator('[0-9]{3}[0-9]{7}', message="Enter a valid 10 digit phone number")]
        }

    def fields_required(self, fields):
        for field in fields:
            if not self.cleaned_data.get(field, ''):
                msg = forms.ValidationError("Please enter " + field)
                self.add_error(field, msg)

    # def clean(self):
    #     cleaned_data = super(ContactForm, self).clean()
    #     subject = self.cleaned_data['subject']
    #     full_name = self.cleaned_data['full_name']
    #     email = self.cleaned_data['email']
    #     phone = self.cleaned_data['phone']
    #     message = self.cleaned_data['message']
    #     print(email, "kerim yaxsi")
    #     is_phone_matched = bool(re.match('[0-9]{3}[0-9]{7}', phone))
    #     print('akif akif akif', is_phone_matched)

    #     if len(phone) < 10 or not is_phone_matched:
    #         print('kerim kerim kerim', is_phone_matched)
    #         self.errors['phone']='Invalid phone number'
    #         raise forms.ValidationError('Your phone is too short')

    #     if len(full_name) < 4:
    #         print("ful")
    #         self._errors['full_name']='Your full name\'s length is too short'
    #         raise forms.ValidationError('Your full name is too short')
            
    #     if len(email) < 7:
    #         print("email")
    #         self._errors['email']='Your email\'s length is too short'
    #         raise forms.ValidationError('Your email is too short')

    #     if(re.match(r'^[a-zA-z0-9_\-\.]+[@][a-z]+[\.][a-z]{5,3}', email)):
    #         print('enail 2')
    #         raise forms.ValidationError('Invalid email address')

    #     if (re.match(r'[0-9]{3}[0-9]{7}', phone)):
    #         print('phone 3')
    #         self._errors['phone']='Invalid phone number'
    #         raise forms.ValidationError('Invalid phone number')


    #     return cleaned_data

src/core/views.py
from django.http.request import HttpRequest
from django.http.response import HttpResponse
from django.shortcuts import render, redirect
from django.urls import translate_url
from django.http import JsonResponse

from django.conf import settings

from core.forms import ContactForm
from core.models import Background, Contact, Feedback, Slider, About, AwesomeCulture

from users.tasks import send_email_task

from django.views.generic import CreateView
from django.views.decorators.cache import cache_page
from product.models import Product
from django.db.models import Q


# def set_language(request, language):    
#     for lang, _ in settings.LANGUAGES:
#         translation.activate(lang)
#         try:
#             view = resolve(urlparse(request.META.get("HTTP_REFERER")).path)
#         except Resolver404:
#             view = None
#         if view:
#             break
#     if view:
#         translation.activate(language)
#         next_url = reverse(view.url_name, args=view.args, kwargs=view.kwargs)
#         response.set_cookie(settings.LANGUAGE_COOKIE_NAME, language)
#         # response = request.COOKIES.get(settings.LANGUAGE_COOKIE_NAME, language)
#         # request.session[translation.LANGUAGE_SESSION_KEY] = language
#         request.session['language'] = language
#         print(request.META.get("HTTP_REFERER"), '----------------------------------------------------------------')
#         response = HttpResponseRedirect(next_url)
#     else:
#         response = HttpResponseRedirect("/")
#     return response


def set_language(request, language, path):
    print(path)
    list_path = path.split("/")
    for path in list_path:
        if path in settings.LANGUAGES:
            list_path.remove(path)
        
    path = "/".join(list_path)
    print(path, '----------------------------------------------------------------')

    lang = request.META.get("HTTP_REFERER", None)
    response = redirect(translate_url(path, language))
    response.set_cookie(settings.LANGUAGE_COOKIE_NAME, language)
    return response

# @cache_page(60 * 15)
def home(request: HttpRequest) -> HttpResponse:
    home_background = Background.objects.all()[0]
    home_background = home_background.home_page
    feedbacks = Feedback.objects.all()[:3]
    sliders = Slider.objects.all()[:4]
    last_product = Product.objects.all()[0]
    context = {
        'title': 'Home',
        'home_background': home_background,
        'feedbacks': feedbacks,
        'sliders': sliders,
        'last_product': last_product
    }
    return render(request, 'core/index.html', context = context)


@cache_page(60 * 15)
def about(request: HttpRequest) -> HttpResponse:
    about_background = Background.objects.all()[0]
    awesomeculture = AwesomeCulture.objects.all()
    about = About.objects.all()[0]
    print(about.main_image.url)
    about_background = about_background.about_page
    context = {
        'title': 'About',
        'about_background': about_background,
        'awesomeculture': awesomeculture,
        'about': about
    }
    return render(request, 'core/about-us.html', context=context)


# @cache_page(60 * 15)
class ContactUs(CreateView):
    template_name = 'core/contact.html'
    form_class = ContactForm   
    contact_background = Background.objects.all()[0].contact_page

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Contact"
        context["form"] = self.form_class
        context["contact_background"] = self.contact_background
        return context

    def form_valid(self, form):
        contact_user = form.save()
        send_email_task(subject="Pavshop Team Notification", email="Your contact form has been saved successfully", user_email=contact_user.email)
        return super(ContactUs, self).form_valid(form) 
    

@cache_page(60 * 15)
# Deprecated view
def contact(request: HttpRequest) -> HttpResponse:
    contact_form = ContactForm()
    contact_background = Background.objects.all()[0]
    
    if request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest' and request.method == 'POST':
        contact_form = ContactForm(request.POST)
        print(request.POST)
        if contact_form.is_valid():
            contact_user= contact_form.save(commit=False)
            send_email_task(subject="Pavshop Team Notification", email="Your contact form has been saved successfully", user_email=contact_user.email)
            contact_user.save()
        else:
            return JsonResponse({"error": contact_form.errors}, status=406)
    
    context = {
        'form': contact_form, 
        'title': 'Contact',
        'contact_background': contact_background.contact_page,
    }
    return render(request, 'core/contact.html', context=context)

src/core/templates/core/contact.html
{% extends 'base.html' %} {% load static %} {% block content %}

<!--======= SUB BANNER =========-->
<section class="sub-bnr" data-stellar-background-ratio="0.5" style="background: url({{ contact_background.url }}) no-repeat;">
  <div class="position-center-center">
    <div class="container">
      <h4>contact us now</h4>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec faucibus
        maximus vehicula. Sed feugiat, tellus vel tristique posuere, diam
      </p>
      <ol class="breadcrumb">
        <li><a href="#">Home</a></li>
        <li class="active">contact</li>
      </ol>
    </div>
  </div>
</section>

<!-- Content -->
<div id="content">
  <!--======= CONATACT  =========-->
  <section class="contact padding-top-100 padding-bottom-100">
    <div class="container">
      <div class="contact-form">
        <h5>PLEASE fill-up FEW details</h5>
        <div class="row">
          <div class="col-md-8">
            <!--======= Success Msg =========-->
            <div id="contact_message" class="success-msg">
              <i class="fa fa-paper-plane-o"></i>Thank You. Your Message has
              been Submitted
            </div>

            <div class="alert alert-danger error_message" style="display: none;" role="alert">
              {{form.non_field_errors}}
              {{form.errors}}
              {{form.error}}
              {{forms.errors}}
              {{form.email.error}}
              {{ form }}
            </div>

            <!--======= FORM  =========-->
            <form role="form" id="contact_form" class="contact-form" method="post" onSubmit="return true">
            {% csrf_token %}
            {% comment %} {% for field in form %}
                <li class="col-sm-6">
                <label>
                  {{field.label}}
                  {{field}}
                </label>
                {% if field.errors %}
                <div class="alert alert-danger">
                  {% for field in form %}
                      {% for error in field.errors %} 
                          <div class="alert alert-danger">
                              <strong>{{ error|escape }}</strong>
                          </div>
                      {% endfor %}
                  {% endfor %}
                </div>
                {% endif %}
                </li>
            {% endfor %} {% endcomment %}
                <li class="col-sm-6">
                  <label>
                    {{form.full_name.label}}
                    {{form.full_name}}
                  </label>
                </li>

                <li class="col-sm-6">
                  <label>
                    {{form.email.label}}
                    {{form.email}}
                  </label>
                </li>

                <li class="col-sm-6">
                  <label>
                    {{form.phone.label}}
                    {{form.phone}}
                  </label>
                </li>

                <li class="col-sm-6">
                  <label>
                    {{form.subject.label}}
                    {{form.subject}}
                  </label>
                </li>

                <li class="col-sm-6">
                  <label>
                    {{form.message.label}}
                    {{form.message}}
                  </label>
                </li>
                <li class="col-sm-12">
                  <button type="submit" value="submit"  class="btn" id="btn_submit">
                    SEND MAIL
                  </button>
                </li>
              </ul>
            </form>
          </div>

          <!--======= ADDRESS INFO  =========-->
          <div class="col-md-4">
            <div class="contact-info">
              <h6>OUR ADDRESS</h6>
              <ul>
                <li>
                  <i class="icon-map-pin"></i> Street No. 12, Newyork 12,<br />
                  MD - 123, USA.
                </li>
                <li><i class="icon-call-end"></i> 1.800.123.456789</li>
                <li>
                  <i class="icon-envelope"></i>
                  <a href="mailto:321kerim123@gmail.com" target="_top"
                    >info@PAVSHOP.com</a
                  >
                </li>
                <li>
                  <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                    Nullam erat turpis, pellentesque non leo eget.
                  </p>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!--======= MAP =========-->
  <div id="map"></div>

  <!-- About -->
  <section class="small-about padding-top-150 padding-bottom-150">
    <div class="container">
      <!-- Main Heading -->
      <div class="heading text-center">
        <h4>about PAVSHOP</h4>
        <p>
          Phasellus lacinia fermentum bibendum. Interdum et malesuada fames ac
          ante ipsumien lacus, eu posuere odio luctus non. Nulla lacinia, eros
          vel fermentum consectetur, risus purus tempc, et iaculis odio dolor in
          ex.
        </p>
      </div>

      <!-- Social Icons -->
      <ul class="social_icons">
        <li>
          <a href="#."><i class="icon-social-facebook"></i></a>
        </li>
        <li>
          <a href="#."><i class="icon-social-twitter"></i></a>
        </li>
        <li>
          <a href="#."><i class="icon-social-tumblr"></i></a>
        </li>
        <li>
          <a href="#."><i class="icon-social-youtube"></i></a>
        </li>
        <li>
          <a href="#."><i class="icon-social-dribbble"></i></a>
        </li>
      </ul>
    </div>
  </section>

 
{% endblock %} {% block js_files %}

<!-- Begin Map Script -->
<script
  type="text/javascript"
  src="http://maps.google.com/maps/api/js?sensor=false"
></script>
<script type="text/javascript">
  /*==========  Map  ==========*/
  var map;
  function initialize_map() {
    if ($("#map").length) {
      var myLatLng = new google.maps.LatLng(-37.814199, 144.96156);
      var mapOptions = {
        zoom: 17,
        center: myLatLng,
        scrollwheel: false,
        panControl: false,
        zoomControl: true,
        scaleControl: false,
        mapTypeControl: false,
        streetViewControl: false,
      };
      map = new google.maps.Map(document.getElementById("map"), mapOptions);
      var marker = new google.maps.Marker({
        position: myLatLng,
        map: map,
        tittle: "Envato",
        icon: "./images/map-locator.png",
      });
    } else {
      return false;
    }
  }
  google.maps.event.addDomListener(window, "load", initialize_map);


  // AJAX 
  $(document).on('submit', '#contact_form', function(e){
    e.preventDefault();
    var csrf_token = $("input[name='csrfmiddlewaretoken']").val();
    var full_name = $("input[name='full_name']:eq(1)").val();
    var email = $("input[name='email']:eq(1)").val();
    var phone = $("input[name='phone']:eq(1)").val();
    var subject = $("input[name='subject']:eq(1)").val();
    var message = $("textarea[name='message']:eq(1)").val();
    console.log(full_name, email, phone, subject, message)
    let successMessage = $('.success-msg');
    let errorMessage = $('.error_message');

    $.ajax({
      type: "POST",
      url: "{% url 'core:contact' %}",
      data: {
        'csrfmiddlewaretoken': csrf_token,
        'full_name': full_name,
        'email': email,
        'phone': phone,
        'subject': subject,
        'message': message
      },
      success: function(response){
        successMessage.css("display", "block");
        errorMessage.css("display", "none");
        
      },
      error: function(response){
        errorMessage.css("display", "block");  
        successMessage.css("display", "none");
        errorMessage.html("");
        if (response["responseJSON"]["error"]){
          $.each(response["responseJSON"]["error"], function(key, value){
            errorMessage.prepend(
          `
            <p>${response["responseJSON"]["error"][key]}</p>
          `
        ); 
          })
        }
      }
    })
  })
</script>

{% endblock %}