src/api/product/urls.py
from django.urls import path, include
from api.product import views



urlpatterns = [

    # Product APIs
    path('', views.ProductListAPIView.as_view(), name='product'),
    path('<int:pk>', views.ProductDetailAPIView.as_view(), name='product_detail'),
    path('create/', views.ProductCreateAPIView.as_view(), name='product_create'),
    path('delete/<int:pk>/', views.ProductDeleteAPIView.as_view(), name='product_delete'),
    path('update/<int:pk>/', views.ProductUpdateAPIView.as_view(), name='product_upadate'),
    path('popular-tags/', views.PopularProductTagsListAPIView.as_view(), name="product_tags"),
    path('new-products/', views.NewProductsListAPIView.as_view(), name="new_products"),
    path('popular-products/', views.PopularProductsListAPIView.as_view(), name="popular_products"),
  

    # Category APIs
    path('category/', views.CategoryListAPIView.as_view(), name='category'),
    path('category/<int:pk>', views.CategoryDetailAPIView.as_view(), name='category_detail'),
    path('category/create/', views.CategoryCreateAPIView.as_view(), name='category_create'),
    path('category/delete/<int:pk>', views.CategoryDeleteAPIView.as_view(), name='category_delete'),
    path('category/update/<int:pk>', views.CategoryUpdateAPIView.as_view(), name='category_update'),

    # Color APIs
    path('color/', views.ColorListAPIView.as_view(), name='color_list'),

    # Brand APIs
    path('brand/', views.BrandListAPIView.as_view(), name='brand_list'),

    # Tag APIs
    path('tag/', views.TagListAPIView.as_view(), name='tag_list'),

]

src/api/urls.py
from django.urls import path, include
from rest_framework_simplejwt.views import TokenRefreshView
from . import views


app_name = "api"

urlpatterns = [
    
    # User  urls
    path('user/', include(("api.users.urls", "api-users")), name='api_users'),

    # Product urls
    path('product/', include(("api.product.urls", "api-product")), name='api_product'),

    # Blog urls
    path("blog/", include(("api.blog.urls", "api-blog")), name="api_blog"),
    
    # Cart
    path('cart/', include('api.cart.urls', "api-urlscart"), name="api_cart"),

    path('about/statistics', views.StatisticsAPIView.as_view(), name="statistics"),
    
    path('about/sponsor', views.AboutSponsorsListApiView.as_view(), name="sponsors"),
    
    path('about/staff', views.AboutStaffListApiView.as_view(), name="staffs"),
]

src/pavshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.i18n import i18n_patterns

# from django.conf.urls import include
from django.urls import re_path
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView



urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin/', admin.site.urls),
    
    path('api/', include('api.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    # Optional UI:
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),

    path('', include('core.urls', namespace='core')),
    path('', include('users.urls')),
    path('blogs/', include('blog.urls', namespace='blogs')),
    path('accounts/', include('users.urls', namespace="users")),
    # path('accounts/', include('allauth.urls')),
    path('', include('order.urls')),
    path('products/', include('product.urls')),
    path('cart/', include('cart.urls')),


    re_path(r'^rosetta/', include('rosetta.urls')),

    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="users/password/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password/password_reset_complete.html'), name='password_reset_complete'),

    path('oauth/', include('social_django.urls', namespace='social')),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)


# if 'rosetta' in settings.INSTALLED_APPS:
#     urlpatterns += [
#         re_path('rosetta/', include('rosetta.urls'))
#     ]

urlpatterns = [
    *i18n_patterns(*urlpatterns, prefix_default_language=False),
    # path("<str:language>/<path:path>/", core_view.set_language, name="set-language"),
    path('i18n/', include('django.conf.urls.i18n')),
]

src/product/urls.py
from django.urls import path
from product import views


app_name = 'products'

urlpatterns = [
    path('', views.ProductListView.as_view(), name = 'products'),
    path('<slug:slug>', views.ProductDetailView.as_view(), name = 'product-detail'),
]

src/product/forms.py
from django import forms
from django.forms import ModelForm
from .models import Review
from django.core.validators import RegexValidator

# Review form on product-detail.html
class ReviewForm(ModelForm):
    class Meta:
        model = Review
        exclude = ['reviewed_at']
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'name': 'name', 'required': 'required'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'name': 'email', 'placeholder':'username@example.com', 'required': 'required'}),
            'review_text': forms.Textarea(attrs={'class':'form-control', 'name': 'review_text', 'placeholder': 'Write...', 'required': 'required'}),
            'product_id': forms.HiddenInput(attrs={'class': 'product_id', 'name': 'product_id'}),
            'rating': forms.HiddenInput(attrs={'class': 'rating-input', 'name':'rating'})
        }
        labels= {
            'name': '*NAME',
            'email': '*EMAIL',
            'review_text': '*YOUR REVIEW',
            'product_id': '',
            'rating': 'YOUR RATING',
        }
        required=(
            'name',
            'email',
            'review_text',
        )
        # validators ={
        #     'email': [RegexValidator('[a-zA-z0-9_\-\.] + [@][a-z]+[\.][a-z]{2,3}',
        #     message='Enter an email in correct format')],
        # }

        def fields_required(self, fields):
            for field in fields:
                if not self.cleaned_data.get(field, ''):
                    msg = forms.ValidationError('Please enter'+ field)
                    self.add_error(field, msg)

        def clean(self):
            try:
                cleaned_data = super(ReviewForm, self).clean()
                name = self.cleaned_data['name']
                email = self.cleaned_data['email']
                review_text = self.cleaned_data['review_text']
                product_id = self.cleaned_data['product_id']
                rating = self.cleaned_data['rating']
                if len(email)< 7:
                    raise forms.ValidationError('Your email is too short')
                return cleaned_data
            except:
                raise forms.ValidationError('')

    

src/api/product/views.py
from rest_framework import generics, permissions, status
from rest_framework.response import Response
from api.product.serializers import (
    ProductSerializer, 
    CategorySerializer,
    ColorSerializer,
    BrandSerializer,
    ProductTagSerializer,
)
from product.models import Product, Category, ProductTag, Color, Brand
from django.db.models import Count, Q


# Category VIEWS
class CategoryListAPIView(generics.ListAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer


class CategoryDetailAPIView(generics.RetrieveAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer
    lookup_field = 'pk'

class CategoryUpdateAPIView(generics.UpdateAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer
    lookup_field = 'pk'

class CategoryDeleteAPIView(generics.DestroyAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer
    lookup_field = 'pk'
    
    def perform_destroy(self, instance):
        super().perform_destroy(instance)

class CategoryCreateAPIView(generics.CreateAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer

# Color VIEWS 
class ColorListAPIView(generics.ListAPIView):
    queryset = Color.objects.all()
    serializer_class = ColorSerializer

# Tag VIEWS
class TagListAPIView(generics.ListAPIView):
    queryset = ProductTag.objects.all()
    serializer_class = ProductTagSerializer

# Brand VIEWS
class BrandListAPIView(generics.ListAPIView):
    queryset = Brand.objects.all()
    serializer_class = BrandSerializer

# Product VIEWS
class ProductListAPIView(generics.ListAPIView):
    """
      
      Method: GET
      Endpoints: api/product/?tag=<str>/       - filter products by tag, expected str
                 api/product/?category=<str>/  - filter products by category, expected str
                 api/product/?color=<list>/    - filter products by color, expected list
                 api/product/?order_by=<str>/  - order by descending, ascending, expected str: "createdat_desc", "createdat_asc", "popularity_asc", "popularity_desc", "price_desc", "price_asc"
                 api/product/?min_price=<int>/ - filter by min price, expected int
                 api/product/?max_price=<int>/ - filter by min price, expected int
                 api/product/?brand=<str>/     - filter by brand, expected str
                 api/product/?new-product=True/- get newest and popular product
    """
    permission_classes = (permissions.AllowAny,)
    

    def get(self, *args, **kwargs):
        queryset = Product.objects.filter(availability=True)

        tag = self.request.query_params.get("tag")  
        category = self.request.query_params.get("category")  
        brand = self.request.query_params.get("brand")  
        color = self.request.query_params.get("color") 
        min_price = self.request.query_params.get("min_price")
        max_price = self.request.query_params.get("max_price")
        new_product = self.request.query_params.get("new-product")
        order_by = self.request.query_params.get("order_by") 
        search_product = self.request.query_params.get("search_product")

        
        if tag:
            queryset = queryset.filter(tag__tag_name=str(tag).lower())
        
        if category:
            queryset = queryset.filter(category__name=str(category))

        if color:
            queryset = queryset.filter(color__name__in=color.split(","))
        
        if brand:
            queryset = queryset.filter(brand__name=str(brand))

        if min_price:
            queryset = queryset.filter(price__gte=float(min_price))
        if max_price:
            queryset = queryset.filter(price__lte=float(max_price))

        if new_product:
            queryset = queryset.order_by('-created_at', '-order_count')[:1]

        if order_by:
            order_by = str(order_by).lower()
            if order_by=="createdat_desc":
                queryset = queryset.order_by("-created_at")
            if order_by=="createdat_asc":
                queryset = queryset.order_by("created_at")
            if order_by=="popularity_desc":
                queryset = queryset.order_by("-order_count")
            if order_by=="popularity_asc":
                queryset = queryset.order_by("order_count")
            if order_by=="price_desc":
                queryset = queryset.order_by("-price")
            if order_by=="price_asc":
                queryset = queryset.order_by("price")
        
        if search_product:
            queryset = queryset.filter(Q(product_name__icontains=search_product) | Q(brief_info__icontains=search_product) | Q(product_info__icontains=search_product))

        serializer = ProductSerializer(queryset, many=True)

        return Response(serializer.data, status=status.HTTP_200_OK)



class PopularProductTagsListAPIView(generics.ListAPIView):
    """
    Endpoint for this api - "api/product/popular-tags/"
    List of 5 popular tags
    """
    queryset = ProductTag.objects.all().order_by("-tag_name__usage_count")[:5]
    serializer_class = ProductTagSerializer
    pagination_class = None


class NewProductsListAPIView(generics.ListAPIView):
    """
    Endpoint for this api - "api/product/new-products/"
    List of 8 new products
    """
    queryset = Product.objects.all().order_by("-created_at")[:8]
    serializer_class = ProductSerializer
    pagination_class = None

class PopularProductsListAPIView(generics.ListAPIView):
    """
    Endpoint for this api - "api/product/new-products/"
    List of 6 popular products
    """
    queryset = Product.objects.all().order_by("-order_count")[:4]
    serializer_class = ProductSerializer
    pagination_class = None



class ProductDetailAPIView(generics.RetrieveAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    lookup_field = 'pk'


class ProductUpdateAPIView(generics.UpdateAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    lookup_field = 'pk'

class ProductDeleteAPIView(generics.DestroyAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    lookup_field = 'pk'
    
    def perform_destroy(self, instance):
        super().perform_destroy(instance)

class ProductCreateAPIView(generics.CreateAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer




# from rest_framework import generics, status, permissions
# from api.serializers import ProductSerializer
# from product.models import Product
# from rest_framework.response import Response

# # in listcreateapiview i need two function in  - get_queryset(self) and post(sel, request, *args, **kwargs)  (for validating data and return response(serializer.data, status))
# # in serializer if i have many querysets i handle it by get_field_name methods() and create method() for taking validated data
# class ProductListCreateApiView(generics.ListCreateAPIView):
#     serializer_class = ProductSerializer
    
#     def get_queryset(self):
#         products = Product.objects.all()
#         return Response(products, status=status.HTTP_200_OK)


#     def post(self, request, *args, **kwargs):
#         serializer = self.get_serializer(data=request.data)
#         serializer.is_valid(raise_exception=True)
#         serializer.save()
#         return Response(serializer.data, status=status.HTTP_201_CREATED)



# class ProductListApiView(generics.ListAPIView):
#     serializer_class = ProductSerializer
    
#     def get_queryset(self):
#         return Product.objects.all()

#     #     paginator_class = CustomPagination()
#     #     # page_obj = paginator_class.get_paginated_response(request, products)

#     #     return Response({'products': products, 'categories': categories, 'popular_tags': popular_tags, 'popular_brands': popular_brands, 'colors': colors, 'page_obj': page_obj, 'title': 'Product List'}, status=status.HTTP_200_OK)
#     #     # return products.union(categories, popular_tags, popular_brands, colors, all=True)


# class ProductCreateApiView(generics.Create):

#     # def get_queryset(self):    
#     #     products = Product.objects.all().order_by('added_date')
#     #     categories = Category.objects.annotate(Count('product')).values_list('name', 'product__count').filter(product__count__gte=1)
#     #     popular_tags = Product.objects.values_list("tag_id__name", flat=True).annotate(Count('tag_id')).order_by('-tag_id__count')[:5]
#     #     popular_brands = Product.objects.values_list("brand_id__name", flat=True).annotate(Count('brand_id')).order_by('-brand_id__count')[:5]
#     #     colors = Color.objects.annotate(Count('product')).values_list('name', 'color').filter(product__count__gte=1)
#     # def get_queryset(self):    
#     #     products = Product.objects.all().order_by('added_date')
#     #     categories = Category.objects.annotate(Count('product')).values_list('name', 'product__count').filter(product__count__gte=1)
#     #     popular_tags = Product.objects.values_list("tag_id__name", flat=True).annotate(Count('tag_id')).order_by('-tag_id__count')[:5]
#     #     popular_brands = Product.objects.values_list("brand_id__name", flat=True).annotate(Count('brand_id')).order_by('-brand_id__count')[:5]
#     #     colors = Color.objects.annotate(Count('product')).values_list('name', 'color').filter(product__count__gte=1)
#     serializer_class = ProductSerializer

#     def perform_create(self, serializer):
#         return super().perform_create(serializer)
    

src/product/templates/product/product_list.html
{% extends 'base.html' %} {% load static %} {% block content %}

<!--======= SUB BANNER =========-->
{% block css_files %} 
  <link rel="stylesheet" href="{% static 'css/filter-price.css' %}">
{% endblock %}
<section
  class="sub-bnr"
  data-stellar-background-ratio="0.5"
  style="background: url({{ product_bg.url }}) no-repeat;"
>
{% csrf_token %}
  <div class="position-center-center">
    <div class="container">
      <h4>PAVSHOP PRODUCTS</h4>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec faucibus
        maximus vehicula. Sed feugiat, tellus vel tristique posuere, diam
      </p>
      <ol class="breadcrumb">
        <li><a href="#">Home</a></li>
        <li class="active">Data</li>
      </ol>
    </div>
  </div>
</section>

<!-- Content -->
<div id="content">
  <!-- Products -->
  <section class="shop-page padding-top-100 padding-bottom-100">
    <div class="container">
      <div class="row">
        <!-- Item Content -->
        <div class="col-sm-9">
          <div class="item-display">
            <div class="row">
              <!-- Products Select -->
              <div class="col-xs-6">
                <div class="pull-left">
                  <!-- Sort By -->
                  <form action="" class="sorting-products" method="get">
                    <select class="selectpicker sortingProduct" id="filter-sorting">
                      <option >Sort By</option>
                      <option name="createdat_asc">Newly added</option>
                      <option name="createdat_desc">Lastly added</option>
                      <option name="popularity_desc">Popular products first</option>
                      <option name="popularity_asc">Popular products at the end</option>
                      <option name="price_asc">From cheap to expensive</option>
                      <option name="price_desc">From expensive to cheap</option>
                    </select>
                  </form>

                  <!-- GRID & LIST -->
                  <a href="#." class="grid-style"><i class="icon-grid"></i></a>
                  <a href="#." class="list-style"><i class="icon-list"></i></a>
                </div>
              </div>
              <div class="col-xs-6 text-right">
                <span class="product-num"
                  >Showing of {{products.count}} products</span
                >
              </div>
            </div>
          </div>

          <!-- Popular Item Slide -->
          <div class="papular-block row single-img-demos" id="productsContainer">
            <!-- Item -->
            {% for product in page_obj %}
            <div class="col-md-4">
              <div class="item">
                <!-- Item img -->
                <div class="item-img">
                  <img
                    class="img-1"
                    src="{{ product.main_image.url }}"
                    alt=""
                  />
                  <!-- Overlay -->
                  <div class="overlay">
                    <div class="position-center-center">
                      <div class="inn">
                        <a href="{{ product.main_image.url }}" data-lighter
                          ><i class="icon-magnifier"></i
                        ></a>
                        <a
                          class="update-basket"
                          href="#."
                          data-product="{{ product.id }}"
                          data-action="add"
                          ><i class="icon-basket"></i
                        ></a>
                        <a
                          class="update-basket"
                          href="#."
                          data-product="{{ product.id }}"
                          data-action="add"
                          ><i class="icon-basket"></i
                        ></a>
                        <a href="#." class="update-whislist" data-product="{{ product.id }}"><i class="icon-heart"></i></a>
                      </div>
                    </div>
                  </div>
                </div>
                <!-- Item Name -->
                <div class="item-name">
                  <a href="{% url 'products:product-detail' product.slug %}"
                    >{{product.product_name}}</a
                  >
                  <p>{{product.brief_info}}</p>
                </div>
                <!-- Price -->
                <span class="price"><small>$</small>{{product.price}}</span>
              </div>
            </div>
            {% endfor %}
          </div>

          <!-- Pagination -->
          <ul class="pagination in-center">
            {% if page_obj.has_previous %}
            <li><a href="products?page=1">&laquo;</a></li>
            <li>
              <a href="products?page={{ page_obj.previous_page_number }}"
                ><i class="fa fa-angle-left"></i
              ></a>
            </li>
            {% endif %} 
            {% for page in page_obj.paginator.page_range %} 
              {% if page == page_obj.number %}
                <li class="active">
                  <a href="products?page={{page}}">{{page}}</a>
                </li>
              {% else %}
                <li><a href="products?page={{page}}">{{page}}</a></li>
              {% endif %} 
            {% endfor %} 
            {% if page_obj.has_next %}
            <li>
              <a href="products?page={{ page_obj.next_page_number }}"
                ><i class="fa fa-angle-right"></i
              ></a>
            </li>
            <li>
              <a href="products?page={{ page_obj.paginator.num_pages }}">
                &raquo;</a
              >
            </li>
            {% endif %}
          </ul>
        </div>

        <!-- Shop SideBar -->
        <div class="col-sm-3">
          <div class="shop-sidebar">
            <!-- Category -->
            <h5 class="shop-tittle margin-bottom-30">category</h5>
            <ul class="shop-cate" id="shop-category">
              {% comment %} {% for category in categories %}
              <li>
                <a href="#."> {{category.0}} <span>{{category.1}}</span></a>
              </li>
              {% endfor %} {% endcomment %}
            </ul>

            <!-- FILTER BY PRICE -->
            <h5 class="shop-tittle margin-top-60 margin-bottom-30">
              FILTER BY PRICE
            </h5>

            <div class="filter-container">
              <div class="row">
                <div class="col-sm-12">
                  <div id="slider-range"></div>
                </div>
              </div>
              <div class="row slider-labels">
                <div class="col-xs-6 caption">
                  <strong>Min:</strong> <span id="slider-range-value1"></span>
                </div>
                <div class="col-xs-6 text-right caption">
                  <strong>Max:</strong> <span id="slider-range-value2"></span>
                </div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <form>
                    <input type="hidden" name="min-value" value="" class="range-price">
                    <input type="hidden" name="max-value" value="" class="range-price">
                  </form>
                </div>
              </div>
            </div>

            <!-- COLORS -->
            <h5 class="shop-tittle margin-top-60 margin-bottom-30">
              FILTER BY COLORS
            </h5>
            <ul class="colors" id="shop-color">
              {% comment %} {% for color in colors %}
              <li>
                <a
                  href="#."
                  style="background:{{color.1}};"
                  data-color-name="{{color.0}}"
                ></a>
              </li>
              {% endfor %} {% endcomment %}
            </ul>

            <!-- TAGS -->
            <h5 class="shop-tittle margin-top-60 margin-bottom-30">
              POPULAR TAGS
            </h5>
            <ul class="shop-tags" id="shop-tag">
              {% comment %} {% for popular_tag in popular_tags %}
              <li><a href="#.">{{popular_tag}}</a></li>
              {% endfor %} {% endcomment %}
            </ul>

            <!-- BRAND -->
            <h5 class="shop-tittle margin-top-60 margin-bottom-30">brands</h5>
            <ul class="shop-cate" id="shop-brand">
              {% comment %} {% for popular_brand in popular_brands %}
              <li><a href="#.">{{popular_brand}}</a></li>
              {% endfor %} {% endcomment %}
            </ul>

            <!-- SIDE BAR BANER -->
            <div class="side-bnr margin-top-50">
              <img class="img-responsive" src="{{ new_product.main_image.url }}" alt="" />
              <div class="position-center-center">
                <span class="price"><small>$</small>{{ new_product.price }}</span>
                <div class="bnr-text"><a href="{% url "products:product-detail" new_product.slug %}">look hot with style</a></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- About -->
  <section class="small-about padding-top-150 padding-bottom-150">
    <div class="container">
      <!-- Main Heading -->
      <div class="heading text-center">
        <h4>about PAVSHOP</h4>
        <p>
          Phasellus lacinia fermentum bibendum. Interdum et malesuada fames ac
          ante ipsumien lacus, eu posuere odio luctus non. Nulla lacinia, eros
          vel fermentum consectetur, risus purus tempc, et iaculis odio dolor in
          ex.
        </p>
      </div>

      <!-- Social Icons -->
      <ul class="social_icons">
        <li>
          <a href="#."><i class="icon-social-facebook"></i></a>
        </li>
        <li>
          <a href="#."><i class="icon-social-twitter"></i></a>
        </li>
        <li>
          <a href="#."><i class="icon-social-tumblr"></i></a>
        </li>
        <li>
          <a href="#."><i class="icon-social-youtube"></i></a>
        </li>
        <li>
          <a href="#."><i class="icon-social-dribbble"></i></a>
        </li>
      </ul>
    </div>
  </section>
  {% endblock %} {% block js_files %}
  <script src="{% static 'js/basket.js' %}"></script>
  <script src="{% static 'js/filterProductAdd.js' %}"></script>
  <script src="{% static 'js/filter-price.js' %}"></script>
  {% comment %} <script src="{% static 'js/whislist.js' %}"></script> {% endcomment %}
  {% endblock js_files %}
</div>